{% set name = "lua-lpeg" %}
{% set version = "1.1.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://luarocks.org/manifests/gvvaughan/lpeg-{{ version }}-1.rockspec
  sha256: 561694b668e7e8b736b86ddaa6788f89585025585de72fbb83aea90ac00d4e0d

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - luarocks
  host:
    - luajit-openresty
  run:
    - luajit-openresty

test:
  commands:
    - luajit -e "require 'lpeg'"

about:
  home: http://www.inf.puc-rio.br/~roberto/lpeg/lpeg.html
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Parsing Expression Grammars For Lua

extra:
  recipe-maintainers:
    - danielnachun
